### ISSUE TITLE
モジュールのパラメタで選択性のものはコードで制限する

### ISSUE THREAD

**Issue by zaki-lknr** [zaki-lknr/esxissh-ansible#12]
[AnsibleModule](https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#ansiblemodule)

ここの`choices`を使って入力値を制限する。

**Comment by zaki-lknr** [comment]
```yaml
      disk:
        - size_gb: 10
          type: thin
```

この`disk`でなくて`disk[].type`の入力を制限ってできるんだっけ
