### ISSUE TITLE
VM情報の取得

### ISSUE THREAD

**Issue by zaki-lknr** [zaki-lknr/esxissh-ansible#13]
# 機能イメージ

[community.vmware.vmware_guest_facts – Gather info about a single VM — Ansible Documentation](https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_facts_module.html)

# 使用コマンド

- `vim-cmd vmsvc/get.guest`
- `vim-cmd vmsvc/get.config`
- `vim-cmd vmsvc/get.environment`

似たコマンドがいくつかある。`get.guest`で良さそうだけど確認。

**Comment by zaki-lknr** [comment]
## get.guest

電源オフだとほとんど取れない

```
[root@localhost:~] vim-cmd vmsvc/get.guest 267
Guest information:

(vim.vm.GuestInfo) {
   toolsStatus = "toolsNotRunning",
   toolsVersionStatus = "guestToolsUnmanaged",
   toolsVersionStatus2 = "guestToolsUnmanaged",
   toolsRunningStatus = "guestToolsNotRunning",
   toolsVersion = "11269",
   toolsInstallType = "guestToolsTypeOpenVMTools",
   toolsUpdateStatus = (vim.vm.GuestInfo.ToolsUpdateStatus) null,
   guestId = <unset>,
   guestFamily = <unset>,
   guestFullName = <unset>,
   hostName = <unset>,
   ipAddress = <unset>,
   net = <unset>,
   ipStack = <unset>,
   disk = <unset>,
   screen = (vim.vm.GuestInfo.ScreenInfo) {
      width = 0,
      height = 0
   },
   guestState = "notRunning",
   powerPolicy = (vim.vm.PowerPolicy) null,
   appHeartbeatStatus = "appStatusGray",
   guestKernelCrashed = false,
   appState = "none",
   guestOperationsReady = false,
   interactiveGuestOperationsReady = false,
   guestStateChangeSupported = false,
   generationInfo = <unset>,
   customizationInfo = (vim.vm.GuestInfo.CustomizationInfo) null
}
[root@localhost:~]
```

**Comment by zaki-lknr** [comment]
他のコマンドも同様に電源オフだと情報はあまり取れなさそう。  
vmxファイルの内容をparseする方が確実っぽい。

**Comment by zaki-lknr** [comment]
vmware_guest_facts は無償ライセンスでも使用可能。

**Comment by zaki-lknr** [comment]
__VMの電源投入前はMACアドレス未確定__

**Comment by zaki-lknr** [comment]
取得サンプルデータ (電源on状態)

```yaml
ok: [localhost] => changed=false 
  instance:
    annotation: ''
    current_snapshot:
      creation_time: '2020-01-22T07:39:54.748667+00:00'
      description: ''
      id: 2
      name: ルーター化完了
      state: poweredOff
    customvalues: {}
    guest_consolidation_needed: false
    guest_question: null
    guest_tools_status: guestToolsRunning
    guest_tools_version: '11269'
    hw_cluster: null
    hw_cores_per_socket: 1
    hw_datastores:
    - WDS100T2B0A
    - cheddar-share
    hw_esxi_host: localhost.naru.jp-z.jp
    hw_eth0:
      addresstype: generated
      ipaddresses:
      - 192.168.0.20
      - fe80::20c:29ff:fe1b:e7e9
      label: Network adapter 1
      macaddress: 00:0c:29:1b:e7:e9
      macaddress_dash: 00-0c-29-1b-e7-e9
      portgroup_key: null
      portgroup_portkey: null
      summary: VM Network
    hw_eth1:
      addresstype: generated
      ipaddresses:
      - 172.16.1.1
      - fe80::20c:29ff:fe1b:e7f3
      label: Network adapter 2
      macaddress: 00:0c:29:1b:e7:f3
      macaddress_dash: 00-0c-29-1b-e7-f3
      portgroup_key: null
      portgroup_portkey: null
      summary: private-network-1
    hw_eth2:
      addresstype: generated
      ipaddresses:
      - 172.29.0.11
      - fe80::202:8294:5475:cd89
      label: Network adapter 3
      macaddress: 00:0c:29:1b:e7:fd
      macaddress_dash: 00-0c-29-1b-e7-fd
      portgroup_key: null
      portgroup_portkey: null
      summary: restricted-network-1
    hw_files:
    - '[WDS100T2B0A] manager-dev/manager-dev.vmx'
    - '[WDS100T2B0A] manager-dev/manager-dev-Snapshot1.vmsn'
    - '[WDS100T2B0A] manager-dev/manager-dev-Snapshot2.vmsn'
    - '[WDS100T2B0A] manager-dev/manager-dev.nvram'
    - '[WDS100T2B0A] manager-dev/manager-dev.vmsd'
    - '[WDS100T2B0A] manager-dev/vmware-22.log'
    - '[WDS100T2B0A] manager-dev/vmware-21.log'
    - '[WDS100T2B0A] manager-dev/vmware-20.log'
    - '[WDS100T2B0A] manager-dev/vmware.log'
    - '[WDS100T2B0A] manager-dev/vmware-17.log'
    - '[WDS100T2B0A] manager-dev/vmware-19.log'
    - '[WDS100T2B0A] manager-dev/vmware-18.log'
    - '[WDS100T2B0A] manager-dev/manager-dev.vmdk'
    - '[WDS100T2B0A] manager-dev/manager-dev-000002.vmdk'
    - '[WDS100T2B0A] manager-dev/manager-dev-000003.vmdk'
    - '[WDS100T2B0A] manager-dev/manager-dev_1.vmdk'
    hw_folder: /ha-datacenter/vm
    hw_guest_full_name: CentOS 7 (64-bit)
    hw_guest_ha_state: null
    hw_guest_id: centos7_64Guest
    hw_interfaces:
    - eth0
    - eth1
    - eth2
    hw_is_template: false
    hw_memtotal_mb: 4096
    hw_name: manager-dev
    hw_power_status: poweredOn
    hw_processor_count: 2
    hw_product_uuid: 564d43e2-b87a-d7c8-921a-3959601be7e9
    hw_version: vmx-13
    instance_uuid: 52b2b413-ec39-c094-c5e2-ce814f38ee3d
    ipv4: 192.168.0.20
    ipv6: null
    module_hw: true
    moid: '45'
    snapshots:
    - creation_time: '2020-01-21T21:44:29.783431+00:00'
      description: ''
      id: 1
      name: multi nic OSインストール直後
      state: poweredOff
    - creation_time: '2020-01-22T07:39:54.748667+00:00'
      description: ''
      id: 2
      name: ルーター化完了
      state: poweredOff
    vimref: vim.VirtualMachine:45
    vnc: {}
```
